// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQEFk-vZKhcngCz3N8YjlQH3gOBAmOwcY',
    appId: '1:783088925292:web:696cf5ccb8db36db777649',
    messagingSenderId: '783088925292',
    projectId: 'qreporting-25ec2',
    authDomain: 'qreporting-25ec2.firebaseapp.com',
    storageBucket: 'qreporting-25ec2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXSfePjTQuOdonQHP6AaOJCAjQckzjshw',
    appId: '1:783088925292:android:aadd1c0359af3548777649',
    messagingSenderId: '783088925292',
    projectId: 'qreporting-25ec2',
    storageBucket: 'qreporting-25ec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtdM3Ghcnir_lyXeavEi9FZWHt2c3p3No',
    appId: '1:783088925292:ios:ff08e9c72342d3a5777649',
    messagingSenderId: '783088925292',
    projectId: 'qreporting-25ec2',
    storageBucket: 'qreporting-25ec2.firebasestorage.app',
    iosBundleId: 'com.example.testingLibs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtdM3Ghcnir_lyXeavEi9FZWHt2c3p3No',
    appId: '1:783088925292:ios:ff08e9c72342d3a5777649',
    messagingSenderId: '783088925292',
    projectId: 'qreporting-25ec2',
    storageBucket: 'qreporting-25ec2.firebasestorage.app',
    iosBundleId: 'com.example.testingLibs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQEFk-vZKhcngCz3N8YjlQH3gOBAmOwcY',
    appId: '1:783088925292:web:f821b7a0dafeb5c4777649',
    messagingSenderId: '783088925292',
    projectId: 'qreporting-25ec2',
    authDomain: 'qreporting-25ec2.firebaseapp.com',
    storageBucket: 'qreporting-25ec2.firebasestorage.app',
  );
}
